version: 2
workflows:
  version: 2
  all:
    jobs:
      - node-latest
      - node8
      - node6
jobs:
  node-latest:
    docker:
      - image: 'circleci/node:9'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: verify
          command: npm run verify
          post:
            - bash <(curl -s https://codecov.io/bash)
      - run:
          name: release
          command: npm run semantic-release || true
  node8:
    docker:
      - image: 'circleci/node:8'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: verify
          command: npm run verify
          post:
            - bash <(curl -s https://codecov.io/bash)
  node6:
    docker:
      - image: 'circleci/node:6'
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: verify
          command: npm run verify
          post:
            - bash <(curl -s https://codecov.io/bash)
